№1

Определите, какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd

In [26]:
move = pd.read_csv('C:/Users/sanar/Desktop/10._Основы_pandas/10._Основы_pandas/Файлы к заданию №1/movies.csv')
move.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [28]:
rating = pd.read_csv('C:/Users/sanar/Desktop/10._Основы_pandas/10._Основы_pandas/Файлы к заданию №1/ratings.csv')
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [30]:
join = rating.merge(move, on='movieId', how='left')
join.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [42]:
join = join[join['rating'] == 5.0]
join.head()

,userId,movieId,rating,timestamp,title,genres
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
6,1,101,5.0,964980868,Bottle Rocket (1996),Adventure|Comedy|Crime|Romance
8,1,151,5.0,964984041,Rob Roy (1995),Action|Drama|Romance|War
9,1,157,5.0,964984100,Canadian Bacon (1995),Comedy|War

In [78]:
gr = join.groupby('movieId').count()
gr.head()

         userId  rating  timestamp  title  genres
movieId
1            47      47         47     47      47
2             7       7          7      7       7
3             6       6          6      6       6
5             3       3          3      3       3
6            24      24         24     24      24

In [84]:
gr.sort_values('userId', ascending = False).head(1)

         userId  rating  timestamp  title  genres
movieId
318         153     153        153    153     153

№2

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. 
Не учитывайте в расчётах отрицательные значения quantity.

In [119]:
pover = pd.read_csv('C:/Users/sanar/Desktop/10._Основы_pandas/10._Основы_pandas/Файлы к заданию №2/power.csv')
pover.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [121]:
pover = pover[pover['country'].isin(['Latvia', 'Lithuania', 'Estonia'])]
pover.head()

       country  year  quantity  category
373  Lithuania  2014      39.0         1
374  Lithuania  2013     192.0         1
375  Lithuania  2012     196.0         1
376  Lithuania  2011     171.0         1
377  Lithuania  2010     158.0         1

In [123]:
pover = pover[pover['category'].isin([4, 12, 21])]
pover.head()

       country  year  quantity  category
10617  Estonia  2008       1.0         4
10618  Estonia  2007       0.0         4
10619  Estonia  2006       0.0         4
10620  Estonia  2005       1.0         4
10621  Estonia  2004       1.0         4

In [125]:
pover = pover[(pover['year'] >= 2005) & (pover['year'] <= 2010)]
pover.head()

         country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4

In [127]:
pover = pover[pover['quantity'] > 0]
pover.head()

         country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [129]:
pover = pover.groupby('country').sum('quantity')
pover.head()

             year  quantity  category
country
Estonia    162590   63440.0      1446
Latvia     142533   54844.0      1491
Lithuania  391484  122296.0      3006

№3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas DataFrame.

In [139]:
tab = pd.read_html('https://www.aviasales.ru/routes/ovb/bkk', decimal = '.', thousands = '')[0]

In [143]:
tab #проблема со шрифтами но формально таблица перенеслась)

,ÐÐµÑÑÑ,Ð Ð¾Ð´Ð½Ñ ÑÑÐ¾ÑÐ¾Ð½Ñ,Ð¢ÑÐ´Ð° Ð¸ Ð¾Ð±ÑÐ°ÑÐ½Ð¾
0,ÐÑÐ»Ñ 2025,29.07.2025 27 620â½,13.07 - 23.07.2025 60 238â½
1,ÐÐ²Ð³ÑÑÑ 2025,21.08.2025 26 633â½,23.08 - 09.09.2025 45 805â½
2,Ð¡ÐµÐ½ÑÑÐ±ÑÑ 2025,02.09.2025 36 800â½,16.09 - 23.09.2025 43 030â½
3,ÐÐºÑÑÐ±ÑÑ 2025,30.10.2025 28 850â½,07.10 - 27.10.2025 49 415â½
4,ÐÐ¾ÑÐ±ÑÑ 2025,02.11.2025 38 057â½,28.11 - 10.12.2025 52 095â½
5,ÐÐµÐºÐ°Ð±ÑÑ 2025,25.12.2025 82 598â½,04.12 - 18.12.2025 55 609â½
6,Ð¯Ð½Ð²Ð°ÑÑ 2026,13.01.2026 28 393â½,18.01 - 31.01.2026 53 763â½
7,Ð¤ÐµÐ²ÑÐ°Ð»Ñ 2026,01.02.2026 Ð¿ÑÐ¾Ð²ÐµÑÐ¸ÑÑ,26.02 - 12.03.2026 60 883â½
8,ÐÐ°ÑÑ 2026,11.03.2026 28 885â½,07.03 - 19.03.2026 51 909â½