№1

Для датафрейма log из материалов занятия создайте столбец source_type по правилам:
Если источник traffic_source равен Yandex или Google, то в source_type ставится organic;
Для источников paid и email из России ставим ad;
Для источников paid и email не из России ставим other;
Все остальные варианты берём из traffic_source без изменений.

In [2]:
import pandas as pd

In [6]:
log = pd.read_csv('C:/Users/sanar/Desktop/доп_материалы_к_пандас_1_и_2/visit_log.csv', sep = ';')
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [8]:
def type(per):
    traffic_source = per['traffic_source']
    region = ['region']
    if traffic_source == 'yandex' or traffic_source == 'google':
        return 'organic'
    elif (region == 'Russia') and (traffic_source == 'paid' or traffic_source == 'email'):
        return 'ad'
    elif (region != 'Russia') and (traffic_source == 'paid' or traffic_source == 'email'):
        return 'other'
    else:
        return traffic_source

In [10]:
log['source_type'] = log.apply(type, axis=1)
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic

№2

В файле URLs.txt содержатся URL страниц новостного сайта. Вам нужно отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри URL конструкцию: /, затем 8 цифр, затем дефис. 

Выполните действия:
Прочитайте содержимое файла с датафрейм.
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствие с заданным шаблоном.

In [13]:
url = pd.read_csv('C:/Users/sanar/Desktop/доп_материалы_к_пандас_1_и_2/URLs.txt')
url.head()

                                                 url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [15]:
import re

In [17]:
url = url.loc[url.url.str.contains(r'/\d{8}-\w+')]
url.head()

                                                 url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

№3

Используйте файл с оценками фильмов ml-latest-small/ratings.csv. 
Посчитайте среднее время жизни пользователей, которые выставили более 100 оценок. 
Под временем жизни понимается разница между максимальным и минимальным значениями столбца timestamp для данного значения userId.

In [20]:
ratings = pd.read_csv('C:/Users/sanar/Desktop/доп_материалы_к_пандас_1_и_2/ml-latest-small/ratings.csv')
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [22]:
users = ratings.groupby('userId').agg({'userId':'count','timestamp':['min','max']})
users.head()

       userId   timestamp
        count         min         max
userId
1          20  1260759108  1260759205
2          76   835355395   835356246
3          51  1298861589  1298932787
4         204   949778714   949982274
5         100  1163373044  1163375145

In [24]:
users = users[users[('userId', 'count')] > 100]
users.head()

       userId   timestamp
        count         min         max
userId
4         204   949778714   949982274
8         116  1154389340  1154474527
15       1700   997937239  1469330735
17        363  1127468587  1127476640
19        423   855190091   855195373

In [26]:
users['vremia_gzizni'] = users.timestamp['max'] - users.timestamp['min']
users.head()

       userId   timestamp             vremia_gzizni
        count         min         max
userId
4         204   949778714   949982274        203560
8         116  1154389340  1154474527         85187
15       1700   997937239  1469330735     471393496
17        363  1127468587  1127476640          8053
19        423   855190091   855195373          5282

In [28]:
users['vremia_gzizni'].mean()

40080507.4496124

№4

Дана статистика услуг перевозок клиентов компании по типам.

Нужно сформировать две таблицы:
Таблицу с тремя типами выручки для каждого client_id без указания адреса клиента;
Аналогичную таблицу по типам выручки с указанием адреса клиента.

In [31]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)
rzd.head()

   client_id  rzd_revenue
0        111         1093
1        112         2810
2        113        10283
3        114         5774
4        115          981

In [33]:
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)
auto.head()

   client_id  auto_revenue
0        113         57483
1        114            83
2        115           912
3        116          4834
4        117            98

In [35]:
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)
air.head()

   client_id  air_revenue
0        115           81
1        116            4
2        117           13
3        118          173

In [36]:
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1',
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)
client_base.head()

   client_id          address
0        111  Комсомольская 4
1        112   Энтузиастов 8а
2        113  Левобережная 1а
3        114          Мира 14
4        115        ЗЖБИиДК 1

In [39]:
rzd_auto = rzd.merge(auto, on='client_id', how='outer')
rzd_auto_air = rzd_auto.merge(air, on='client_id', how='outer')
rzd_auto_air.head()

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           NaN          NaN
1        112       2810.0           NaN          NaN
2        113      10283.0       57483.0          NaN
3        114       5774.0          83.0          NaN
4        115        981.0         912.0         81.0

In [41]:
rzd_auto_air_client_base = rzd_auto_air.merge(client_base, on='client_id', how='outer')
rzd_auto_air_client_base.head()

   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           NaN          NaN  Комсомольская 4
1        112       2810.0           NaN          NaN   Энтузиастов 8а
2        113      10283.0       57483.0          NaN  Левобережная 1а
3        114       5774.0          83.0          NaN          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1